// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRWzikE9_k-yiZx_chBVPs5RtPaWpOX-c',
    appId: '1:989044489106:web:843694e262f5cb36e4df4b',
    messagingSenderId: '989044489106',
    projectId: 'ingre-chef',
    authDomain: 'ingre-chef.firebaseapp.com',
    storageBucket: 'ingre-chef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA82r475Vl-GhyR3GU3mcfth4u2wGkkSY',
    appId: '1:989044489106:android:40db422c6e6b0b96e4df4b',
    messagingSenderId: '989044489106',
    projectId: 'ingre-chef',
    storageBucket: 'ingre-chef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeIfJ-jF7hkBOgghOnVWnBOtHPWWAeC5I',
    appId: '1:989044489106:ios:68fa44e003bd48f0e4df4b',
    messagingSenderId: '989044489106',
    projectId: 'ingre-chef',
    storageBucket: 'ingre-chef.appspot.com',
    iosBundleId: 'com.example.main',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeIfJ-jF7hkBOgghOnVWnBOtHPWWAeC5I',
    appId: '1:989044489106:ios:68fa44e003bd48f0e4df4b',
    messagingSenderId: '989044489106',
    projectId: 'ingre-chef',
    storageBucket: 'ingre-chef.appspot.com',
    iosBundleId: 'com.example.main',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRWzikE9_k-yiZx_chBVPs5RtPaWpOX-c',
    appId: '1:989044489106:web:be1be1ead9f2ecb0e4df4b',
    messagingSenderId: '989044489106',
    projectId: 'ingre-chef',
    authDomain: 'ingre-chef.firebaseapp.com',
    storageBucket: 'ingre-chef.appspot.com',
  );

}